routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/post/{id}', ['as'=>'home.post','uses'=>'AdminPostsController@post']);

Route::group(['middleware' => 'admin'], function () {
    Route::get('/admin', function () {
        return view('admin.index');
    });
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/category', 'AdminCategoryController');
    Route::resource('admin/media', 'AdminMediaController');
    
    Route::resource('admin/comments', 'PostCommentsController');
    Route::resource('admin/comment/replies', 'CommentRepliesController');
});

Route::group(['middleware' => ['auth']], function () {
    Route::post('comment/reply',['as'=>'comment.reply','uses'=>'CommentRepliesController@createReply']);
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable=[
        'post_id',
        'author',
        'email',
        'photo',
        'body',
        'is_active',
    ];

    public function replies()
    {
        return $this->hasMany('App\CommentReply');
    }
    public function posts()
    {
        return $this->belongsTo('App\Post');
    }
}

resources/views/admin/comments/index.blade.php
@extends('layouts/admin')

@section('content')
    <h1>All Comments</h1>
    @if (count($comments) > 0)
    <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Comments</th>
                    <th>Created at</th>
                    <th>View Post</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($comments as $comment)
                <tr>
                    <th>{{$comment->id}}</th>
                    <th>{{$comment->body}}</th>
                    <th>{{$comment->created_at->diffForHumans()}}</th>
                    <th><a href="{{route('home.post',$comment->id)}}">View Post</a></th>
                    @if ($comment->is_active == 0)
                        <th>
                            <form action="{{route('comments.update',['id'=>$comment->id])}}" method="POST">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="is_active" value="1">
                                <button class="btn btn-primary">Approve</button>
                            </form>
                        </th>
                    @else
                        <th>
                            <form action="{{route('comments.update',['id'=>$comment->id])}}" method="POST">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="is_active" value="0">
                                <button class="btn btn-warning">Un-Approve</button>
                            </form>
                        </th>
                    @endif
                        <th>
                            <form action="{{route('comments.destroy',['id'=>$comment->id])}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" value="DELETE">Delete</button>
                            </form>
                        </th>
                </tr>
                @endforeach

            </tbody>
        </table>
        @else
        <h1 class="text-center">No Comments</h1>
    @endif
    
    
@endsection

resources/views/admin/comments/show.blade.php
@extends('layouts/admin')

@section('content')
    <h1>Comments {{$post->title}}</h1>
    @if (count($comments) > 0)
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Comments</th>
                <th>Created at</th>
                <th>View Post</th>
                <th>View Replies</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($comments as $comment)
            <tr>
                <th>{{$comment->id}}</th>
                <th>{{$comment->body}}</th>
                <th>{{$comment->created_at->diffForHumans()}}</th>
                <th><a href="{{route('home.post',$comment->id)}}">View Post</a></th>
                <th><a href="{{route('replies.show',$comment->id)}}">View Replies</a></th>
                @if ($comment->is_active == 0)
                    <th>
                        <form action="{{route('comments.update',['id'=>$comment->id])}}" method="POST">
                            @csrf
                            @method('PUT')
                            <input type="hidden" name="is_active" value="1">
                            <button class="btn btn-primary">Approve</button>
                        </form>
                    </th>
                @else
                    <th>
                        <form action="{{route('comments.update',['id'=>$comment->id])}}" method="POST">
                            @csrf
                            @method('PUT')
                            <input type="hidden" name="is_active" value="0">
                            <button class="btn btn-warning">Un-Approve</button>
                        </form>
                    </th>
                @endif
                    <th>
                        <form action="{{route('comments.destroy',['id'=>$comment->id])}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" value="DELETE">Delete</button>
                        </form>
                    </th>
            </tr>
            @endforeach

        </tbody>
    </table>
    @else
        <h1 class="text-center">No Comment</h1>
    @endif
    
@endsection