routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/post/{id}', ['as'=>'home.post','uses'=>'AdminPostsController@post']);

Route::group(['middleware' => 'admin'], function () {
    Route::get('/admin', function () {
        return view('admin.index');
    });
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/category', 'AdminCategoryController');
    Route::resource('admin/media', 'AdminMediaController');
    
    Route::resource('admin/comments', 'PostCommentsController');
    Route::resource('admin/comment/replies', 'CommentRepliesController');
});

Route::group(['middleware' => ['auth']], function () {
    Route::post('comment/reply',['as'=>'comment.reply','uses'=>'CommentRepliesController@createReply']);
});

app/Post.php
<?php

namespace App;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => ['user.name','title'],
                'save_to'=>'slug',
                'on_update'=>true,
            ]
        ];
    }
    protected $fillable =[
        'user_id','category_id','photo_id','title','body',
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }
    public function photo()
    {
        return $this->belongsTo('App\Photo');
    }
    public function category()
    {
        return $this->belongsTo('App\Category');
    }
    public function comments()
    {
        return $this->hasMany('App\Comment');
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts/admin')

@section('content')
    <h1>create posts</h1>
    @include('includes.tinyeditor')
    @include('includes.form_error_message')
    <form class="form-horizontal" action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label class="control-label col-sm-2" for="title">Title</label>
          <div class="col-sm-10">
          <input type="text" class="form-control" id="title" placeholder="Enter title" name="title" value="{{old('title')}}">
          </div>
        </div>
        <div class="form-group">
                <label class="control-label col-sm-2" for="category">Category</label>
                <select class="form-control col-sm-10" id="option" name="category_id">
                    @foreach ($cats as $cat)
                    <option value="{{$cat->id}}">{{$cat->name}}</option>
                    @endforeach
                </select>
            </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="file">User Image</label>
            <input class="col-sm-10" type="file" class="form-control-file" id="file" name="photo_id">
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="body">Description</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="body" id="body" cols="30" rows="10"></textarea>
            </div>
            
        </div>

        <div class="form-group">        
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary btn-lg">Create Post</button>
          </div>
        </div>
      </form>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts/admin')

@section('content')
    <h1>Edit Post</h1>
    <div class="row">
      <div class="col-sm-3">
        <img class="img-responsive img-rounded" height="50" src="{{$post->photo ? $post->photo->file : "/images/400.png" }}" alt="">
      </div>
      <div class="col-sm-9">
      @include('includes.form_error_message')
      <form class="form-horizontal" action="{{route('posts.update',['id'=>$post->id])}}" method="POST" enctype="multipart/form-data">
          @csrf
          @method('PUT')
          <div class="form-group">
            <label class="control-label col-sm-2" for="title">Title</label>
            <div class="col-sm-10">
            <input type="text" class="form-control" id="title" placeholder="Enter title" name="title" value="{{$post->title}}">
            </div>
          </div>
          <div class="form-group">
                  <label class="control-label col-sm-2" for="category">Category</label>
                  <select class="form-control col-sm-10" id="option" name="category_id">
                      @foreach ($cats as $cat)
                      <option value="{{$cat->id}}">{{$cat->name}}</option>
                      @endforeach
                  </select>
              </div>
          <div class="form-group">
              <label class="control-label col-sm-2" for="file">User Image</label>
          <input class="col-sm-10" type="file" class="form-control-file" id="file" name="photo_id">
          </div>
          <div class="form-group">
              <label class="control-label col-sm-2" for="body">Description</label>
              <div class="col-sm-10">
              <textarea class="form-control" name="body" id="body" cols="30" rows="10">{{$post->body}}</textarea>
              </div>
              
          </div>

          <div class="form-group">        
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary btn-lg">update Post</button>
            </div>
          </div>
          
        </form>
        <form action="{{route('posts.destroy',['id'=>$post->id])}}" method="POST">
            @csrf
            @method('DELETE')
            <button id="form-delete" type="submit" class="btn btn-danger btn-lg" value="DELETE">Delete Post</button>
          </form>
      </div>
    </div>


    

    
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts/admin')

@section('content')
    <h1>posts</h1>

    <table class="table">
            <thead>
              <tr>
                <th>Id</th>
                <th>Nama</th>
                <th>Category Id</th>
                <th>Photo</th>
                <th>Title</th>
                <th>Body</th>
                <th>Created at</th>
                <th>Update at</th>
              </tr>
            </thead>
            <tbody>
                @if ($posts)
                    @foreach ($posts as $post)
                        <tr>
                            <td>{{$post->id}}</td>
                            <td>{{$post->user->name}}</td>
                            <td>{{$post->category ? $post->category->name : 'belum terkategori'}}</td>
                            <td><img height="50" src="{{$post->photo ? $post->photo->file : "/images/400.png"}}" alt=""></td>
                            <td><a href="posts/{{$post->id}}/edit">{{$post->title}}</a></td>
                            <td>{{Str::limit($post->body,5)}}</td>
                            <td>{{$post->created_at->diffForHumans()}}</td>
                            <td>{{$post->updated_at->diffForHumans()}}</td>
                            <td><a href="{{route('home.post',['id'=>$post->slug])}}">view post</a></td>
                            <td><a href="{{route('comments.show',['id'=>$post->id])}}">view comment</a></td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
          </table>
          <div class="text-center">
            
             {{$posts->render()}}
          </div>
@endsection