routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/post/{id}', ['as'=>'home.post','uses'=>'AdminPostsController@post']);

Route::group(['middleware' => 'admin'], function () {
    Route::get('/admin', function () {
        return view('admin.index');
    });
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/category', 'AdminCategoryController');
    Route::resource('admin/media', 'AdminMediaController');
    
    Route::resource('admin/comments', 'PostCommentsController');
    Route::resource('admin/comment/replies', 'CommentRepliesController');
});

Route::group(['middleware' => ['auth']], function () {
    Route::post('comment/reply',['as'=>'comment.reply','uses'=>'CommentRepliesController@createReply']);
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable= [
        'name',
    ];

    
}

resources/views/admin/categories/edit.blade.php
@extends('layouts/admin')

@section('content')
    <h1>Edit Categories</h1>
   

<form class="form-horizontal" action="{{route('category.update',['id'=>$cat->id])}}" method="POST">
    @csrf
    @method('PUT')
    <div class="form-group">
        <label class="control-label col-sm-2" for="name">Nama Kategori</label>
        <div class="col-sm-10">
        <input type="text" class="form-control" id="name" placeholder="Nama Kategori" name="name" value="{{$cat->name}}">
        </div>
    </div>
    <div class="form-group">        
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary btn-lg">Update Category</button>
            
        </div>
    </div>
</form>
<form action="{{route('category.destroy',['id'=>$cat->id])}}" method="POST">
        @csrf
        @method("DELETE")

            <button id="form-delete" type="submit" class="btn btn-danger btn-lg" value="DELETE">delete Category</button>

    </form>
    
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts/admin')

@section('content')
    <h1>Categories</h1>
   <div class="col-sm-6">
    <form class="form-horizontal" action="{{route('category.store')}}" method="POST">
        @csrf
        <div class="form-group">
            <label class="control-label col-sm-2" for="name">Nama Kategori</label>
            <div class="col-sm-10">
            <input type="text" class="form-control" id="name" placeholder="Nama Kategori" name="name" value="{{old('name')}}">
            </div>
        </div>
        <div class="form-group">        
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary btn-lg">Create Category</button>
            </div>
          </div>
    </form>
   </div>
   <div class="col-sm-6">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Kategori</th>
                <th>Dibuat pada</th>
            </tr>
        </thead>
        <tbody>
            @if ($cats)
                @foreach ($cats as $cat)
                    <tr>
                        <th>{{$cat->id}}</th>
                        <th><a href="{{route('category.edit',['id'=>$cat->id])}}">{{$cat->name}}</a></th>
                        <th>{{$cat->created_at ? $cat->created_at->diffForHumans() : "none"}}</th>
                    </tr>
                @endforeach
            @endif
        </tbody>
    </table>
   </div>
    
@endsection